### ISSUE TITLE
structure of the train data

### ISSUE THREAD

**Issue by haibucuo0** [jesusNPL/RS-SDM_ENM#1]
Hi, I want to know the structure of the train data.For instance, for ENM, when use S-RS data,  x are CHIRPS,LAI,NDVI,MAT,MAP and altitude，what y is it? And for SDM，what y is it?
Thanks.

**Comment by jesusNPL** [comment]
Hi, I do not know if I totally understood your question, however if you are trying to build an ENM/SDM you should provide the coordinates of your species. So, following a linear model notation Y = β1 + β2X + ϵ, yes, Y = the coordinates and X is your predictor.

**Comment by haibucuo0** [comment]
thank you. 
I mean, when building a model to predict species distribution, what are the independent variables (x)and what are the dependent variables(y).
